const subjects = {
  tenth: {
    major: {
      accounting: [
        "fundamentals_of_fluency",
        "english",
        "civic_education",
        "math",
        "religion",
        "physical_education",
        "information_technology",
        "indonesian",
        "art",
        "conversation",
        "history",
        "fundamentals_of_science_and_social",
        "mandarin",
      ],
      softwareEngineering: [
        "math",
        "english",
        "mandarin",
        "fundamentals_of_fluency",
        "civic_education",
        "physical_education",
        "religion",
        "history",
        "conversation",
        "indonesian",
        "art",
        "fundamentals_of_science_and_social",
        "information_technology",
      ],
    },
  },
  eleventh: {
    major: {
      accounting: [
        "indonesian",
        "ap",
        "creative_entrepreneurial_products",
        "english",
        "physical_education",
        "history",
        "pal",
        "computerized_accounting",
        "conversation",
        "financial_accounting",
        "religion",
        "math",
        "civic_education",
        "banking",
        "mandarin",
        "microsoft",
        "taxation",
      ],
      softwareEngineering: [
        "math",
        "english",
        "mandarin",
        "web",
        "database",
        "oop",
        "mobile",
        "civic_education",
        "physical_education",
        "religion",
        "history",
        "conversation",
        "indonesian",
        "creative_entrepreneurial_products",
        "microsoft",
      ],
    },
  },
  twelfth: {
    major: {
      accounting: [
        "ap",
        "computerized_accounting",
        "indonesian",
        "banking",
        "english",
        "civic_education",
        "taxation",
        "financial_accounting",
        "conversation",
        "pal",
        "math",
        "religion",
      ],
      softwareEngineering: [
        "creative_entrepreneurial_products",
        "oop",
        "database",
        "web",
        "english",
        "mobile",
        "conversation",
        "math",
        "civic_education",
        "religion",
        "indonesian",
      ],
    },
  },
};

export default subjects;
